### ISSUE TITLE
Transfer images 

### ISSUE THREAD

**Issue by SureshbabuAkash1999** [BugsForDays/libsonyapi#1]
How to transfer images to ubuntu pc via this API.

**Comment by petabite** [comment]
Hello,

Thanks for asking. There is actually a quite comprehensive step-by-step located in the Sony Camera API Reference documentation, but I can give you a quick summary on how to get it going.

1. The first step is to change the camera function to content transfer. Here is an in-depth flow provided in the API reference

<img width="700" alt="image" src="https://user-images.githubusercontent.com/24444266/115919205-603c9a00-a42d-11eb-9c59-999abf3e9eb4.png">

**pg. 282**


With the API, after you've set up a `Camera` object, you can do:

```python
camera.do("setCameraFunction", "Contents Transfer")
```

You may also call `camera.do("getStorageInformation")` to check if the media is inserted.

2. Next, you need to get the storage source of your camera:
``` python
source = camera.do("getSourceList", { "scheme": "storage"})["result"][0][0]["source"] # should be a string with the source uri
```

3. Get the contents of your storage (date view). Here is a sample flow from the docs:

<img width="700" alt="image" src="https://user-images.githubusercontent.com/24444266/115922023-2f5e6400-a431-11eb-8229-9bd494226caa.png">

**pg. 283**

In the code:
``` python
contents = camera.do("getContentList", { "uri": source, "stIdx": 0, "cnt": 50, "view": "date", "sort": ""} )
```
You should now have uris for specific date folders in your storage. More info about the params and the format of the JSON response of the `getContentList` function can be found in the Sony Camera API documentation.

4. Download images

After traversing the date "folders" by looping through each date folder in the `contents` from the last step. You should be able to get to a list of images. The response should look something like this:

<img width="797" alt="image" src="https://user-images.githubusercontent.com/24444266/115923010-77ca5180-a432-11eb-884b-cf0476a7939e.png">

**pg. 204**

Now, you can just send a request from your code to the URLs at `smallUrl`, `largeUrl`, or `thumbnailUrl` to download the images you want.

This isn't a comprehensive guide on how to get it working and I definitely recommend taking a look at the Sony Camera API Docs for how to do this (see section below). The code snippets also have not been tested and some debugging may be necessary especially since some functions depend on your specific camera model.

### Sony Camera API Docs
For more information about the details, I recommend downloading the Sony Camera Remote API SDK [here](https://developer.sony.com/file/download/sony-camera-remote-api-beta-sdk-2/). After unzipping, you should find a pdf document named "Sony_CameraRemoteAPIbeta_API-Reference."

Some important pages:
- info about Transferring Images - pg. 20
- Transfer Image specific functions - pg. 195
- `getContentList` - pg. 200
- Transfer Image sample sequence flows - pg. 282

Hope that helps.

**Comment by SureshbabuAkash1999** [comment]
I can't thank you enough sir for your positive response and support. You literally saved my day. Sir, I just have one more query. I am using a raspberry pie which runs on ubuntu. To use this SDK we just have to import it using pip command right ? Or are there any more steps to do to get my camera connected. If so please guide me through the same. I know it's a bit too much to ask from my side. I'm extremely sorry for the same. I have developed a GUI application using bloodevil's github repo. Now I can control the zoom of the camera and capture the image only. It is in my github account.

**Comment by petabite** [comment]
Yea, no worries. Yep, you can install with the `pip` command. As long as your Pi is connected to the camera via wifi, you should be good. The quick start code in the README should get you started.

**Comment by SureshbabuAkash1999** [comment]
Thank a lot for your reply, Sir.
